#!/bin/bash

#PBS -N training
#PBS -j oe 
#PBS -l nodes=1:ppn=1:gpus=1:exclusive_process 
#PBS -l walltime=24:00:00:00 
#PBS -q dept_gpu

echo Running on `hostname`
echo workdir $PBS_O_WORKDIR
echo ld_library_path $LD_LIBRARY_PATH

#for some reason when the job starts on the node, it auto-cd's to your home dir
cd $PBS_O_WORKDIR

pdb=`sed -n "${PBS_ARRAYID}p" pdbs`
qsub -t 1-17 run.pbs

echo $cmd
$cmd

exit


exit
